scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: apps
  scrape_interval: 5s
  static_configs:
  - targets:
    - gateway:5000
    - products:5000